spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: account
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: resource
          uri: lb://resource-service
          predicates:
            - Path=/resource/**
        - id: search
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: audio
          uri: lb://audio-service
          predicates:
            - Path=/audio/**,/playlists/**,/comments/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8765/eureka}

auth:
  service-id: auth-service