spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: account
          uri: lb://account-service
          predicates:
            - Path=/profiles/**
        - id: resource
          uri: lb://resource-service
          predicates:
            - Path=/images/**,/audio/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8765/eureka
